<<<<<<< HEAD
name: CI with SonarCloud
=======
name: SonarCloud Scan
>>>>>>> 204fe348592be4c8ac05a857d99b4e4fb270e083

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
<<<<<<< HEAD
  build-and-sonar:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Configurar Node.js (ou Java se for backend)
=======
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
>>>>>>> 204fe348592be4c8ac05a857d99b4e4fb270e083
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
<<<<<<< HEAD

      # 3️⃣ Instalar dependências
      - name: Install dependencies
        run: npm install

      # 4️⃣ Rodar testes (opcional)
      - name: Run tests
        run: npm test

      # 5️⃣ Analisar código no SonarCloud
=======
      - run: npm install
>>>>>>> 204fe348592be4c8ac05a857d99b4e4fb270e083
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=EDUSTREAM-N3
            -Dsonar.organization=rafaelbandoch
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.branch.name=main
