name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v5.3.1
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=edustream-n3
            -Dsonar.projectKey=rafaelbandoch
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
